language: python

sudo: false

matrix:
  include:
  - python: "3.5"
    env:
      - WXPYTHON_SNAPSHOTS=https://wxpython.org/Phoenix/snapshot-builds/linux/gtk3/ubuntu-14.04/

notifications:
  email: false

before_install:
  - echo "-----before_install-----"

install:
  - echo "-----install-----"

  # Start the install of everything
  - pip install --upgrade pip wheel
  - "pip install --only-binary :all: --pre -f $WXPYTHON_SNAPSHOTS wxPython"
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install coveralls
  - pip install numpy

script:
  - green pybank -vvv --run-coverage --processes 1

after_success:
  # Send coverage information to coveralls.io
  - coveralls
