language: python

sudo: false

python:
  - "3.4"

notifications:
  email: false

before_install:
  - echo "-----before_install-----"

install:
  - echo "-----install-----"
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt
  - pip install coveralls
  - pip install wheel
  - pip install numpy
  #- pip install "wxPython_Phoenix-3.0.3.dev1820+49a8884.tar.gz"
  - pip install --upgrade --pre --trusted-host wxpython.org -f http://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix

script:
#  - nosetests --verbose --with-cov --cov pybank --logging-level=INFO
  - green pybank -vv --run-coverage

after_success:
  # Send coverage information to coveralls.io
  - coveralls

#addons:
#  artifacts: true

addons:
  apt:
    packages:
      - libghc-gstreamer-dev
      - dpkg-dev
      - libnotify
      - libsdl1.2-dev